{% set name = "nionui" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #Use pypi for the next release, source distribution missing files
  #url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  #sha256: 85c4a64e6a30be2b601f05680e809712589c6dbb561426d4d5e0f35ef5f97e54
  url: https://github.com/nion-software/nionui/archive/{{ version }}.tar.gz
  sha256: 4b38253bee3613a0e94bf6395f21a4c4b4036939b09bf1bbc19cfd18aa9237ea

build:
  number: 0
  noarch: python
  entry_points:
    - nionui=nion.ui.command:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - imageio
    - nionutils >=0.3.19
    - numpy
    - python >=3.6

test:
  imports:
    - nion.ui
    - nion.ui.test

about:
  home: https://github.com/nion-software/nionui
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Nion UI framework.
  dev_url: https://github.com/nion-software/nionui

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
